spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://fcbayern1.github.io/
          predicates:
            - Query=url,sb
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: f9216742-6363-4b13-84b1-51c5d52b5a8c
        group: default
  config:
    import:
      - optional:nacos:mall-gateway.yml # ?? DEFAULT_GROUP:mall-coupon.yml
      - optional:nacos:datasource.yml?group=dev
      - optional:nacos:mybatis.yml?group=dev
      - optional:nacos:other.yml?group=dev

server:
  port: 88