spring:
  application:
    name: mall_gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  #实现路径重写
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: f9216742-6363-4b13-84b1-51c5d52b5a8c
        group: default
  config:
    import:
      - optional:nacos:mall-gateway.yml # ?? DEFAULT_GROUP:mall-coupon.yml
      - optional:nacos:datasource.yml?group=dev
      - optional:nacos:mybatis.yml?group=dev
      - optional:nacos:other.yml?group=dev

server:
  port: 88